const $=id=>document.getElementById(id);let token=localStorage.getItem('cl_token');let me=null;let socket=null;let room=null;let state=null;let resultShown=false;let authMode='login';let createMode='SIMPLE';let muted=localStorage.getItem('cl_mute')==='1';let audioCtx=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const show=id=>document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('hidden',x.id!==id));
const toast=msg=>{const n=document.createElement('div');n.className='toastItem';n.textContent=msg;$('toast').appendChild(n);setTimeout(()=>n.remove(),3000)};
const errText=e=>({USERNAME_3:'Username ต้องมีอย่างน้อย 3 ตัวอักษร',PASSWORD_INVALID:'Password อย่างน้อย 6 ตัวและต้องตรงกัน',USERNAME_EXISTS:'Username นี้ถูกใช้แล้ว',INVALID_LOGIN:'Username หรือ Password ไม่ถูกต้อง',ROOM_NOT_FOUND:'ไม่พบห้อง',ROOM_FULL:'ห้องเต็ม',GAME_ALREADY_STARTED:'เกมเริ่มแล้ว',ALL_PLAYERS_MUST_READY:'ผู้เล่นทุกคนต้อง READY',NEED_TWO_PLAYERS:'ต้องมีอย่างน้อย 2 คน',HOST_ONLY:'เฉพาะ HOST',CANNOT_LEAVE_DURING_GAME:'ออกจากห้องระหว่างเกมไม่ได้',STALE_STATE:'สถานะเกมเก่า กรุณารอสักครู่',GAME_PAUSED:'เกมหยุดชั่วคราวเพราะผู้เล่นหลุด',DRAW_FOUR_COLOR_REQUIRED:'ต้องเลือกสีของ Draw Four',INVALID_CARD:'ลงการ์ดนี้ไม่ได้',CARD_NOT_OWNED:'การ์ดนี้ไม่ได้อยู่ในมือคุณ',NOT_YOUR_TURN:'ยังไม่ถึงตาคุณ',INSERT_WINDOW_CLOSED:'หมดช่วง INSERT',STACK_TYPE_MISMATCH:'ต้อง Stack ชนิดเดียวกัน',COLOR_MISMATCH:'สีไม่ตรงเงื่อนไข',MUST_RESOLVE_PLUS:'ต้องจัดการ Plus ก่อน'}[e]||e);
async function api(path,opts={}){const res=await fetch(path,{...opts,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...(opts.headers||{})}});const j=await res.json().catch(()=>({}));if(!res.ok)throw new Error(j.error||`HTTP_${res.status}`);return j;}
function beep(kind='tap'){if(muted)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();const f={tap:440,play:620,draw:260,special:780,error:140,win:980}[kind]||440;o.frequency.value=f;o.type='sine';g.gain.value=.035;o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.09);}catch{}}
function setMute(v){muted=v;localStorage.setItem('cl_mute',v?'1':'0');$('muteBtn').textContent=v?'🔇':'🔊'}setMute(muted);
function connect(){
 if(!token)return;
 if(typeof io!=='function')return toast('ไม่พบระบบ Realtime (Socket.IO)');
 if(socket)socket.disconnect();
 socket=io({auth:{token},transports:['websocket','polling'],reconnection:true,reconnectionAttempts:Infinity,reconnectionDelay:500,reconnectionDelayMax:5000,timeout:10000});
 socket.on('connect',()=>{
   if(room?.room_code) socket.emit('JOIN_ROOM',{code:room.room_code});
 });
 socket.on('connect_error',(err)=>toast(`เชื่อมต่อ Realtime ไม่สำเร็จ: ${err?.message||'unknown error'}`));
 socket.on('ROOM_UPDATED',r=>{room=r;renderRoom();});socket.on('GAME_STARTED',()=>{resultShown=false;beep('special');show('game');loadChat();});socket.on('GAME_STATE',s=>{state=s;renderGame();});socket.on('GAME_META',()=>{});socket.on('GAME_PAUSED',({userId})=>{beep('error');$('pauseBanner').textContent=userId===me.id?'คุณหลุด — กำลังรอการเชื่อมต่อ':'ผู้เล่นหลุด — เกมหยุดจนกว่าจะกลับมา';$('pauseBanner').classList.remove('hidden');});socket.on('GAME_ACTION_ACCEPTED',()=>beep('play'));socket.on('GAME_ACTION_REJECTED',x=>{beep('error');if(x.state){state=x.state;renderGame();}toast(errText(x.reason));});socket.on('CHAT_MESSAGE_CREATED',m=>appendChat(m));socket.on('ERROR',e=>toast(errText(e.error)));socket.on('KICKED',()=>{room=null;localStorage.removeItem('cl_room');show('lobby');toast('คุณถูกนำออกจากห้อง');});socket.on('disconnect',()=>{});}
function emit(name,payload={}){if(!socket||!socket.connected)return toast('ยังไม่ได้เชื่อมต่อเซิร์ฟเวอร์');socket.emit(name,payload);}
function loginUI(){show('auth');$('loginTab').classList.toggle('active',authMode==='login');$('registerTab').classList.toggle('active',authMode==='register');$('confirmWrap').classList.toggle('hidden',authMode==='login');$('authSubmit').textContent=authMode==='login'?'ENTER CIRCUS':'CREATE ACCOUNT';}
function bootHome(){show('home');$('homeGreeting').textContent=me.display_name||me.username;$('homeName').textContent=me.display_name;$('homeAvatar').textContent=me.avatar;$('homePoints').textContent=me.league_points;$('homeWins').textContent=me.wins;$('homeStats').textContent=`@${me.username} · ID ${me.id.slice(0,8)}`;connect();}
$('loginTab').onclick=()=>{authMode='login';loginUI()};$('registerTab').onclick=()=>{authMode='register';loginUI()};
$('authForm').onsubmit=async e=>{e.preventDefault();$('authMsg').textContent='';try{const body={username:$('username').value,password:$('password').value,confirmPassword:$('confirmPassword').value};const j=await api(authMode==='login'?'/api/login':'/api/register',{method:'POST',body:JSON.stringify(body)});token=j.token;me=j.user;localStorage.setItem('cl_token',token);bootHome();const saved=localStorage.getItem('cl_room');if(saved){try{const r=await api(`/api/rooms/${saved}`);room=r.room;show('room');connect();}catch{localStorage.removeItem('cl_room')}}}catch(e){$('authMsg').textContent=errText(e.message)}};
$('logoutBtn').onclick=()=>{socket?.disconnect();socket=null;token=null;me=null;room=null;state=null;localStorage.removeItem('cl_token');localStorage.removeItem('cl_room');loginUI()};$('muteBtn').onclick=()=>setMute(!muted);$('profileBtn').onclick=async()=>{show('profile');$('profileDisplayName').value=me.display_name;$('profileAvatarInput').value=me.avatar;$('profileAvatar').textContent=me.avatar;await loadHistory()};$('profileBack').onclick=()=>bootHome();
$('playBtn').onclick=()=>show('lobby');$('lobbyBack').onclick=()=>bootHome();$('createBtn').onclick=()=>{$('createPanel').classList.remove('hidden');$('joinPanel').classList.add('hidden')};$('joinBtn').onclick=()=>{$('joinPanel').classList.remove('hidden');$('createPanel').classList.add('hidden')};document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{createMode=b.dataset.mode;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x===b));});
$('confirmCreate').onclick=async()=>{try{const j=await api('/api/rooms',{method:'POST',body:JSON.stringify({mode:createMode,maxPlayers:Number($('maxPlayers').value),turnTimerSeconds:Number($('turnTimer').value)})});room=j.room;localStorage.setItem('cl_room',room.room_code);show('room');connect()}catch(e){toast(errText(e.message))}};
$('confirmJoin').onclick=async()=>{try{const code=$('roomCodeInput').value.trim().toUpperCase();const j=await api('/api/rooms/join',{method:'POST',body:JSON.stringify({code})});room=j.room;localStorage.setItem('cl_room',room.room_code);show('room');connect()}catch(e){toast(errText(e.message))}};
$('leaveRoom').onclick=()=>{emit('LEAVE_ROOM');localStorage.removeItem('cl_room');room=null;state=null;show('lobby')};$('readyBtn').onclick=()=>emit('TOGGLE_READY');$('startBtn').onclick=()=>emit('START_GAME');$('roomSettingsBtn').onclick=()=>openRoomSettings();
$('roomChatForm').onsubmit=e=>{e.preventDefault();const v=$('roomChatInput').value.trim();if(v)emit('CHAT_MESSAGE',{message:v});$('roomChatInput').value=''};$('gameChatForm').onsubmit=e=>{e.preventDefault();const v=$('gameChatInput').value.trim();if(v)emit('CHAT_MESSAGE',{message:v});$('gameChatInput').value=''};
$('gameChatToggle').onclick=()=>{$('gameChat').classList.toggle('hidden')};$('closeGameChat').onclick=()=>{$('gameChat').classList.add('hidden')};$('gameLeaveBtn').onclick=()=>{show('room');loadChat()};$('drawBtn').onclick=()=>sendAction({type:'DRAW_CARD'});$('passBtn').onclick=()=>sendAction({type:'PASS'});$('circusBtn').onclick=()=>sendAction({type:'CALL_CIRCUS'});$('drawPile').onclick=()=>sendAction({type:'DRAW_CARD'});
$('leagueBtn').onclick=loadLeague;$('leagueBack').onclick=bootHome;$('howBtn').onclick=()=>showInfo('HOW TO PLAY',`<h3>Core rules</h3><ul><li>Letter cards match by letter or current color.</li><li>DOUBLE +2 stacks only DOUBLE; TRIPLE +3 stacks only TRIPLE; Draw Four +4 stacks only Draw Four.</li><li>BACKWORD reverses direction and can reflect a plus effect when the color is correct.</li><li>JOKER copies the latest discard ability. JOKER BACKWORD copies then reverses. JOKER x2 executes the copied ability twice sequentially.</li><li>RESET +2 ALL makes every other player draw 2, resets the played/draw pool, then searches for a LETTER start without triggering revealed specials.</li><li>When you have one card, call CIRCUS. Another player can call against you first, causing 5 cards.</li><li>INSERT is server-locked and only opens after a played card; exact same letter+color is required for letter insertion.</li><li>No Skull system.</li><li>When the draw pile cannot be rebuilt, LAST DANCE begins. PASS is available only there.</li><li>Disconnect pauses the match; no bot or substitute takes the seat.</li></ul>`);$('settingsBtn').onclick=()=>showInfo('SETTINGS',`<h3>Local settings</h3><p>Sound: use the speaker button in the top bar. The preference is stored on this device.</p><p>Room timer is configurable when creating a room and is stored server-side. The timeout action is deliberately not guessed because the rules do not define what timeout should do.</p>`);$('infoBack').onclick=bootHome;$('modalClose').onclick=()=>$('modal').classList.add('hidden');$('saveProfile').onclick=async()=>{try{const j=await api('/api/profile',{method:'PATCH',body:JSON.stringify({displayName:$('profileDisplayName').value,avatar:$('profileAvatarInput').value})});me=j.user;toast('Profile saved');$('profileAvatar').textContent=me.avatar}catch(e){toast(errText(e.message))}};
function renderRoom(){if(!room)return;show(state?'game':'room');$('roomCodeTitle').textContent=room.room_code;$('roomCodeBig').textContent=room.room_code;$('roomMode').textContent=room.mode;const mine=room.players.find(p=>p.user_id===me.id);$('readyBtn').textContent=mine?.ready?'READY ✓':'READY';$('startBtn').classList.toggle('hidden',room.host_id!==me.id||!['WAITING','FINISHED'].includes(room.status));$('roomSettingsBtn').classList.toggle('hidden',room.host_id!==me.id||room.status!=='WAITING');$('players').innerHTML=room.players.map(p=>`<div class="player"><span class="playerAvatar">${esc(p.avatar)}</span><span class="playerInfo"><b>${esc(p.display_name)}</b><small>@${esc(p.username)} ${p.ready?'· READY':''} ${p.host_id===room.host_id?'':''}</small></span>${p.user_id===room.host_id?'<span class="hostBadge">HOST</span>':''}<span class="dot ${p.connected?'on':''}"></span>${room.host_id===me.id&&p.user_id!==me.id&&room.status==='WAITING'?`<button data-kick="${p.user_id}">KICK</button>`:''}</div>`).join('');$('players').querySelectorAll('[data-kick]').forEach(b=>b.onclick=()=>emit('KICK_PLAYER',{userId:b.dataset.kick}));loadChat();}
async function loadChat(){if(!room)return;try{const j=await api(`/api/rooms/${room.room_code}/chat`);$('roomChat').innerHTML='';$('gameChatLog').innerHTML='';j.messages.forEach(appendChat)}catch{}}
function appendChat(m){const html=`<div class="chatMsg"><span>${esc(m.avatar||'🎪')}</span><div class="bubble"><b>${esc(m.displayName||'System')}</b> <small>${new Date(m.createdAt||m.created_at).toLocaleTimeString()}</small><div>${esc(m.message)}</div></div></div>`;if($('roomChat')){$('roomChat').insertAdjacentHTML('beforeend',html);$('roomChat').scrollTop=$('roomChat').scrollHeight}$('gameChatLog')?.insertAdjacentHTML('beforeend',html);if($('gameChatLog'))$('gameChatLog').scrollTop=$('gameChatLog').scrollHeight}
function cardClass(c){return c?.color?c.color.toLowerCase():''}function cardLabel(c){if(!c)return '';if(c.type==='LETTER')return c.letter;if(c.type==='DOUBLE')return '+2';if(c.type==='TRIPLE')return '+3';if(c.type==='DRAW_FOUR')return '+4';if(c.type==='BACKWORD')return '↶';if(c.type==='SKIP')return 'SKIP';if(c.type==='JOKER')return 'JOKER';if(c.type==='JOKER_BACKWORD')return 'JOKER ↶';if(c.type==='JOKER_X2')return 'JOKER ×2';if(c.type==='RESET_PLUS2_ALL')return 'RESET +2';return c.type}
function cardHTML(c,playable=false,insertable=false){return `<div class="card ${cardClass(c)} ${playable?'playable':''} ${insertable?'insertable':''} ${!playable&&!insertable?'disabled':''}" data-card="${esc(c.id)}"><span class="corner">${esc(c.color||'★')}</span><span class="main">${esc(cardLabel(c))}</span></div>`}
function renderGame(){if(!state)return;show('game');const mine=state.players.find(p=>p.id===me.id);const current=state.players.find(p=>p.id===state.currentPlayerId);$('turnLabel').textContent=state.phase==='INSERT_WINDOW'?'INSERT WINDOW':state.phase==='LAST_DANCE'?'LAST DANCE':current?.id===me.id?'YOUR TURN':`${current?.name||'—'}'S TURN`;$('phaseLabel').textContent=state.phase;$('directionLabel').textContent=state.direction==='CW'?'↻ CLOCKWISE':'↺ REVERSE';$('drawCount').textContent=state.drawPile.length;$('pauseBanner').classList.toggle('hidden',state.phase!=='PAUSED');$('passBtn').classList.toggle('hidden',state.phase!=='LAST_DANCE');$('drawBtn').disabled=!(state.phase==='FIRST_TURN'||state.phase==='PLAYING'||state.phase==='INSERT_WINDOW')||state.currentPlayerId!==me.id||state.phase==='PAUSED';$('circusBtn').disabled=mine?.hand.length!==1||mine?.circusCalled;const passAllowed=state.phase==='LAST_DANCE'&&state.currentPlayerId===me.id&&!(mine?.hand||[]).some(c=>approxPlayable(c,state.discardPile?.at(-1)));$('passBtn').disabled=!passAllowed;$('myCount').textContent=`(${mine?.hand.length||0})`;
 $('opponents').innerHTML=state.players.filter(p=>p.id!==me.id).map(p=>`<div class="opp ${p.id===state.currentPlayerId?'active':''}"><div class="name">${esc(p.avatar)} ${esc(p.name)}</div><div class="cards">${p.hand.length} cards</div>${p.hand.length===1&&!p.circusCalled?'<div class="circusCall">CIRCUS READY</div>':''}${p.hand.length===1&&!p.circusCalled&&state.phase!=='GAME_FINISHED'?`<button data-circus-target="${p.id}" style="margin-top:5px">CALL!</button>`:''}</div>`).join('');$('opponents').querySelectorAll('[data-circus-target]').forEach(b=>b.onclick=()=>sendAction({type:'CALL_CIRCUS',targetPlayerId:b.dataset.circusTarget}));
 const top=state.discardPile?.at(-1);$('discardCard').className=`card ${cardClass(top)}`;$('discardCard').innerHTML=top?`<span class="corner">${esc(top.color||'★')}</span><span class="main">${esc(cardLabel(top))}</span>`:'';
 $('effectBar').textContent=state.pendingEffect?`PENDING ${state.pendingEffect.stackType} · ${state.pendingEffect.amount} → ${state.players.find(p=>p.id===state.pendingEffect.targetPlayerId)?.name||'—'}`:state.currentColor?`COLOR ${state.currentColor}`:'';$('gameHint').textContent=state.phase==='INSERT_WINDOW'?'INSERT is live — server accepts the first valid request.':state.phase==='PAUSED'?'Waiting for every player to reconnect…':state.phase==='LAST_DANCE'?'No rebuild: play a card if possible, otherwise PASS.':'';
 const canTurn=state.currentPlayerId===me.id&&(state.phase==='FIRST_TURN'||state.phase==='PLAYING'||state.phase==='INSERT_WINDOW'||state.phase==='LAST_DANCE');const canInsert=state.phase==='INSERT_WINDOW'&&state.insertWindow?.eligiblePlayers?.includes(me.id);$('myHand').innerHTML=(mine?.hand||[]).map(c=>{const approx=canTurn&&approxPlayable(c,top);const ins=canInsert&&approxInsertable(c,top);return cardHTML(c,approx,ins)}).join('');$('myHand').querySelectorAll('[data-card]').forEach(el=>el.onclick=()=>{const c=mine.hand.find(x=>x.id===el.dataset.card);if(canInsert&&approxInsertable(c,top))return sendPlay(c,true);if(canTurn&&approxPlayable(c,top))return sendPlay(c,false);});
 if(state.phase==='GAME_FINISHED'&&!resultShown){resultShown=true;beep('win');openResult();}}
function approxPlayable(c,t){if(!c)return false;if(c.type==='RESET_PLUS2_ALL'||['JOKER','JOKER_BACKWORD','JOKER_X2'].includes(c.type))return true;if(state.pendingEffect){if(c.type!==state.pendingEffect.stackType)return false;if(c.type=== 'DRAW_FOUR')return true;return c.color===state.pendingEffect.color}if(c.type==='DRAW_FOUR')return true;if(['DOUBLE','TRIPLE'].includes(c.type))return !t||c.color===state.currentColor||c.type===t.type||c.color===t.color;if(['BACKWORD','SKIP'].includes(c.type))return c.color===state.currentColor;if(c.type==='LETTER')return c.letter===t?.letter||c.color===state.currentColor;return false}
function approxInsertable(c,t){if(['JOKER','JOKER_BACKWORD','JOKER_X2'].includes(c.type))return false;if(state.pendingEffect){if(c.type!==state.pendingEffect.stackType)return false;if(c.type==='DRAW_FOUR')return true;return c.color===state.pendingEffect.color}if(c.type==='LETTER')return c.letter===t?.letter&&c.color===state.currentColor;return c.color===state.currentColor&&['BACKWORD','SKIP'].includes(c.type)}
function sendPlay(c,insert){if(c.type==='DRAW_FOUR')return colorModal(c,insert);sendAction({type:insert?'INSERT_CARD':'PLAY_CARD',cardId:c.id})}function colorModal(c,insert){openModal('CHOOSE COLOR',`<p>Draw Four requires a color.</p><div class="colorChoices">${['RED','YELLOW','GREEN','BLUE'].map(col=>`<button class="${col}" data-color="${col}">${col}</button>`).join('')}</div>`);document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{closeModal();sendAction({type:insert?'INSERT_CARD':'PLAY_CARD',cardId:c.id,chosenColor:b.dataset.color})})}
function sendAction(a){if(!state)return;emit('GAME_ACTION',{...a,clientActionId:crypto.randomUUID(),stateVersion:state.version});}
function openResult(){const r=state.result||[];const rows=r.slice().sort((a,b)=>(a.rank??99)-(b.rank??99)).map(x=>`<div class="historyRow"><b>${esc(state.players.find(p=>p.id===x.userId)?.name||x.userId)}</b><small>${x.points} points · ${x.cards} cards ${x.win?'· WIN':''}</small></div>`).join('');openModal('GAME OVER',`<p>${state.winnerId?`Winner: <b>${esc(state.players.find(p=>p.id===state.winnerId)?.name||'—')}</b>`:'LAST DANCE ended with no winner.'}</p>${rows}<button class="primary wide" id="resultRoom">BACK TO ROOM</button>`);$('resultRoom').onclick=()=>{closeModal();state=null;resultShown=false;show('room');loadChat()}}
function openModal(title,body){$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modal').classList.remove('hidden')}function closeModal(){$('modal').classList.add('hidden')}
function openRoomSettings(){openModal('ROOM SETTINGS',`<div class="formPanel"><label>Max players<select id="setMax">${[2,3,4,5,6,7,8].map(n=>`<option ${n===room.settings.maxPlayers?'selected':''}>${n}</option>`).join('')}</select></label><label>Timer<select id="setTimer">${[0,30,60,120,300].map(n=>`<option value="${n}" ${n===room.settings.turnTimerSeconds?'selected':''}>${n?`${n} sec`:'Off'}</option>`).join('')}</select></label><button id="saveRoomSettings" class="primary">SAVE</button></div>`);$('saveRoomSettings').onclick=async()=>{try{const j=await api(`/api/rooms/${room.room_code}/settings`,{method:'PATCH',body:JSON.stringify({maxPlayers:Number($('setMax').value),turnTimerSeconds:Number($('setTimer').value)})});room=j.room;closeModal();renderRoom()}catch(e){toast(errText(e.message))}}}
async function loadLeague(){try{const j=await api('/api/league');show('league');$('seasonName').textContent=j.season.name;$('ranking').innerHTML=j.ranking.length?j.ranking.map((r,i)=>`<div class="rankRow"><span class="rankNum">#${i+1}</span><span class="rankPlayer">${esc(r.avatar)} ${esc(r.display_name)}</span><b>${r.points}</b><small>${r.wins}W</small></div>`).join(''):'<p class="muted">No league games yet.</p>';$('seasonHistory').innerHTML=j.seasons.map(s=>`<div class="seasonRow"><b>${esc(s.name)}</b><div>${s.status==='CLOSED'?`<span class="champ">👑 ${esc(s.champion_name||'—')}</span>`:'ACTIVE'}</div></div>`).join('')}catch(e){toast(errText(e.message))}}
async function loadHistory(){try{const j=await api('/api/profile/history');$('matchHistory').innerHTML=j.history.length?j.history.map(h=>`<div class="historyRow"><b>${h.mode} · ${new Date(h.created_at).toLocaleString()}</b><small>${h.myResult.points} pts · ${h.myResult.cards} cards ${h.myResult.win?'· WIN':''}</small></div>`).join(''):'<p class="muted">No completed matches yet.</p>'}catch(e){$('matchHistory').textContent='Could not load history.'}}
function showInfo(title,html){show('info');$('infoTitle').textContent=title;$('infoBody').innerHTML=html}
(async()=>{loginUI();if(token){try{const j=await api('/api/me');me=j.user;bootHome();const saved=localStorage.getItem('cl_room');if(saved){const r=await api(`/api/rooms/${saved}`);room=r.room;show('room');connect()}}catch{token=null;localStorage.removeItem('cl_token')}}})();
