import express from 'express';
import http from 'node:http';
import path from 'node:path';
import crypto from 'node:crypto';
import {Server} from 'socket.io';
import db from './db.js';
import {createUser,findUser,getUser,signToken,verifyPassword,verifyToken,newId} from './auth.js';
import {initialState,visibleState,validateAction,applyAction,scoreGame} from './game.js';

const app=express();const server=http.createServer(app);const io=new Server(server,{cors:{origin:true,credentials:true},maxHttpBufferSize:1e6});
app.use(express.json({limit:'64kb'}));
app.get('/',(req,res)=>res.sendFile(path.resolve('index.html')));
app.get('/app.js',(req,res)=>res.sendFile(path.resolve('app.js')));
app.get('/style.css',(req,res)=>res.sendFile(path.resolve('style.css')));
const now=()=>new Date().toISOString();
const normUsername=s=>String(s||'').trim().toLowerCase().replace(/[^a-z0-9_-]/g,'').slice(0,24);
const authRate=new Map();
function authGuard(req,res,next){const key=(req.ip||'unknown')+':'+req.path;const t=Date.now();const a=authRate.get(key)||[];const fresh=a.filter(x=>t-x<60000);if(fresh.length>=20)return res.status(429).json({error:'RATE_LIMIT'});fresh.push(t);authRate.set(key,fresh);next();}
const roomCode=()=>crypto.randomBytes(4).toString('hex').slice(0,6).toUpperCase();
function requireAuth(req,res,next){try{req.user=verifyToken(String(req.headers.authorization||'').replace(/^Bearer\s+/i,''));next();}catch{res.status(401).json({error:'UNAUTHORIZED'});}}
function roomByCode(code){return db.prepare('SELECT * FROM rooms WHERE room_code=?').get(String(code||'').toUpperCase());}
function roomPlayers(roomId){return db.prepare(`SELECT rp.*,p.display_name,p.avatar,u.username FROM room_players rp JOIN profiles p ON p.user_id=rp.user_id JOIN users u ON u.id=rp.user_id WHERE rp.room_id=? ORDER BY rp.seat`).all(roomId);}
function publicRoom(r){return {...r,settings:JSON.parse(r.settings_json),players:roomPlayers(r.id)};}
function gameByRoom(roomId){return db.prepare('SELECT * FROM games WHERE room_id=? ORDER BY created_at DESC LIMIT 1').get(roomId);}
function saveGame(gid,state,status=state.phase){db.prepare('UPDATE games SET state_json=?,state_version=?,status=?,updated_at=? WHERE id=?').run(JSON.stringify(state),state.version,status,now(),gid);}
function emitGame(room,state){for(const p of state.players){const s=connections.get(p.id);if(s)s.emit('GAME_STATE',visibleState(state,p.id));}io.to(room.room_code).emit('GAME_META',{phase:state.phase,version:state.version});}
function systemChat(roomId,message){db.prepare('INSERT INTO chat_messages(room_id,user_id,message,kind,created_at) VALUES(?,?,?,?,?)').run(roomId,'SYSTEM',message,'SYSTEM',now());}
function broadcastRoom(roomId){const r=db.prepare('SELECT * FROM rooms WHERE id=?').get(roomId);if(r)io.to(r.room_code).emit('ROOM_UPDATED',publicRoom(r));}
function currentSeason(){let s=db.prepare("SELECT * FROM seasons WHERE status='ACTIVE' ORDER BY start_date DESC LIMIT 1").get();if(!s){s={id:newId(),name:'Season 1',start_date:now(),end_date:null,total_games:100,status:'ACTIVE',champion_id:null};db.prepare('INSERT INTO seasons(id,name,start_date,total_games,status,champion_id) VALUES(?,?,?,?,?,?)').run(s.id,s.name,s.start_date,100,'ACTIVE',null);}return s;}
function closeSeason(season){const rows=db.prepare(`SELECT ls.user_id,ls.points,ls.wins,p.display_name,p.avatar FROM league_stats ls JOIN profiles p ON p.user_id=ls.user_id WHERE ls.season_id=? ORDER BY ls.points DESC,ls.wins DESC,ls.games_played ASC`).all(season.id);const champion=rows[0]?.user_id||null;db.prepare("UPDATE seasons SET status='CLOSED',end_date=?,champion_id=? WHERE id=?").run(now(),champion,season.id);const n=Number(season.name.match(/\d+/)?.[0]||1)+1;db.prepare('INSERT INTO seasons(id,name,start_date,total_games,status) VALUES(?,?,?,?,?)').run(newId(),`Season ${n}`,now(),100,'ACTIVE');return champion;}
function finalizeGame(room,g,state){if(g.status==='GAME_FINISHED'||g.finished_at)return;const result=scoreGame(state);const resultMap=new Map(result.map(x=>[x.userId,x]));db.prepare('INSERT INTO game_history(id,game_id,room_id,mode,result_json,created_at) VALUES(?,?,?,?,?,?)').run(newId(),g.id,room.id,g.mode,JSON.stringify(result),now());
 if(g.mode==='LEAGUE'){const season=currentSeason();const tx=db.transaction(()=>{for(const r of result){db.prepare(`INSERT INTO league_stats(season_id,user_id,points,wins,games_played) VALUES(?,?,?,?,?) ON CONFLICT(season_id,user_id) DO UPDATE SET points=points+excluded.points,wins=wins+excluded.wins,games_played=games_played+1`).run(season.id,r.userId,r.points,r.win,1);db.prepare('UPDATE profiles SET league_points=league_points+?,wins=wins+? WHERE user_id=?').run(r.points,r.win,r.userId);} });tx();const count=db.prepare('SELECT COUNT(*) n FROM game_history gh JOIN games g ON g.id=gh.game_id WHERE gh.mode=\'LEAGUE\' AND gh.created_at>=?').get(season.start_date).n;if(count>=season.total_games){closeSeason(season);}}
 return resultMap;
}

app.get('/api/health',(req,res)=>res.json({ok:true,service:'circus-lungjun-beta'}));
app.post('/api/register',authGuard,(req,res)=>{try{const username=normUsername(req.body.username);const password=String(req.body.password||'');const confirm=String(req.body.confirmPassword||password);if(username.length<3)return res.status(400).json({error:'USERNAME_3'});if(password.length<6||password!==confirm)return res.status(400).json({error:'PASSWORD_INVALID'});if(findUser(username))return res.status(409).json({error:'USERNAME_EXISTS'});const u=createUser(username,password);res.json({token:signToken(u),user:getUser(u.id)});}catch(e){res.status(500).json({error:'REGISTER_FAILED'});}});
app.post('/api/login',authGuard,(req,res)=>{const u=findUser(normUsername(req.body.username));if(!u||!verifyPassword(String(req.body.password||''),u.password_hash))return res.status(401).json({error:'INVALID_LOGIN'});res.json({token:signToken(u),user:getUser(u.id)});});
app.get('/api/me',requireAuth,(req,res)=>res.json({user:getUser(req.user.sub)}));
app.patch('/api/profile',requireAuth,(req,res)=>{const displayName=String(req.body.displayName||'').trim().slice(0,24)||req.user.username;const avatar=[...String(req.body.avatar||'🎪')].slice(0,2).join('');db.prepare('UPDATE profiles SET display_name=?,avatar=? WHERE user_id=?').run(displayName,avatar,req.user.sub);res.json({user:getUser(req.user.sub)});});
app.get('/api/profile/history',requireAuth,(req,res)=>{const rows=db.prepare(`SELECT gh.*,g.mode,g.created_at AS game_created FROM game_history gh JOIN games g ON g.id=gh.game_id WHERE json_extract(gh.result_json,'$[*].userId') IS NOT NULL ORDER BY gh.created_at DESC LIMIT 50`).all();const mine=rows.map(r=>{const result=JSON.parse(r.result_json);return {...r,myResult:result.find(x=>x.userId===req.user.sub)||null};}).filter(x=>x.myResult);res.json({history:mine});});
app.post('/api/rooms',requireAuth,(req,res)=>{const mode=req.body.mode==='LEAGUE'?'LEAGUE':'SIMPLE';let code=roomCode();while(roomByCode(code))code=roomCode();const id=newId(),settings={maxPlayers:Math.min(8,Math.max(2,Number(req.body.maxPlayers)||8)),turnTimerSeconds:Math.max(0,Math.min(300,Number(req.body.turnTimerSeconds)||0)),allowChat:true};db.prepare('INSERT INTO rooms(id,room_code,host_id,mode,status,settings_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(id,code,req.user.sub,mode,'WAITING',JSON.stringify(settings),now(),now());db.prepare('INSERT INTO room_players(room_id,user_id,seat,ready,connected,joined_at,last_seen_at) VALUES(?,?,?,?,?,?,?)').run(id,req.user.sub,0,0,1,now(),now());res.json({room:publicRoom(db.prepare('SELECT * FROM rooms WHERE id=?').get(id))});});
app.post('/api/rooms/join',requireAuth,(req,res)=>{const r=roomByCode(req.body.code);if(!r)return res.status(404).json({error:'ROOM_NOT_FOUND'});if(r.status==='FINISHED')return res.status(409).json({error:'ROOM_FINISHED'});const existing=db.prepare('SELECT * FROM room_players WHERE room_id=? AND user_id=?').get(r.id,req.user.sub);if(!existing){if(r.status!=='WAITING')return res.status(409).json({error:'GAME_ALREADY_STARTED'});const n=db.prepare('SELECT COUNT(*) n FROM room_players WHERE room_id=?').get(r.id).n;if(n>=JSON.parse(r.settings_json).maxPlayers)return res.status(409).json({error:'ROOM_FULL'});db.prepare('INSERT INTO room_players(room_id,user_id,seat,ready,connected,joined_at,last_seen_at) VALUES(?,?,?,?,?,?,?)').run(r.id,req.user.sub,n,0,1,now(),now());}res.json({room:publicRoom(r)});});
app.get('/api/rooms/:code',requireAuth,(req,res)=>{const r=roomByCode(req.params.code);if(!r)return res.status(404).json({error:'ROOM_NOT_FOUND'});if(!db.prepare('SELECT 1 FROM room_players WHERE room_id=? AND user_id=?').get(r.id,req.user.sub))return res.status(403).json({error:'NOT_MEMBER'});res.json({room:publicRoom(r)});});
app.get('/api/rooms/:code/chat',requireAuth,(req,res)=>{const r=roomByCode(req.params.code);if(!r||!db.prepare('SELECT 1 FROM room_players WHERE room_id=? AND user_id=?').get(r.id,req.user.sub))return res.status(403).json({error:'NOT_MEMBER'});const messages=db.prepare(`SELECT c.id,c.message,c.kind,c.created_at,p.display_name,p.avatar FROM chat_messages c LEFT JOIN profiles p ON p.user_id=c.user_id WHERE c.room_id=? ORDER BY c.id DESC LIMIT 100`).all(r.id).reverse();res.json({messages});});
app.patch('/api/rooms/:code/settings',requireAuth,(req,res)=>{const r=roomByCode(req.params.code);if(!r||r.host_id!==req.user.sub)return res.status(403).json({error:'HOST_ONLY'});if(r.status!=='WAITING')return res.status(409).json({error:'ROOM_ALREADY_STARTED'});const old=JSON.parse(r.settings_json);const settings={...old,maxPlayers:Math.min(8,Math.max(2,Number(req.body.maxPlayers)||old.maxPlayers)),turnTimerSeconds:Math.min(300,Math.max(0,Number(req.body.turnTimerSeconds)||0))};db.prepare('UPDATE rooms SET settings_json=?,updated_at=? WHERE id=?').run(JSON.stringify(settings),now(),r.id);broadcastRoom(r.id);res.json({room:publicRoom({...r,settings_json:JSON.stringify(settings)})});});
app.get('/api/league',requireAuth,(req,res)=>{const s=currentSeason();const ranking=db.prepare(`SELECT ls.user_id,ls.points,ls.wins,ls.games_played,p.display_name,p.avatar FROM league_stats ls JOIN profiles p ON p.user_id=ls.user_id WHERE ls.season_id=? ORDER BY ls.points DESC,ls.wins DESC,ls.games_played ASC`).all(s.id);const seasons=db.prepare(`SELECT s.*,p.display_name AS champion_name FROM seasons s LEFT JOIN profiles p ON p.user_id=s.champion_id ORDER BY s.start_date DESC LIMIT 20`).all();res.json({season:s,ranking,seasons});});

const connections=new Map();
io.use((socket,next)=>{try{socket.user=verifyToken(socket.handshake.auth?.token);next();}catch{next(new Error('UNAUTHORIZED'));}});
io.on('connection',socket=>{
 const uid=socket.user.sub;connections.set(uid,socket);let joined=null;
 socket.on('JOIN_ROOM',({code})=>{const r=roomByCode(code);if(!r)return socket.emit('ERROR',{error:'ROOM_NOT_FOUND'});if(!db.prepare('SELECT 1 FROM room_players WHERE room_id=? AND user_id=?').get(r.id,uid))return socket.emit('ERROR',{error:'NOT_MEMBER'});joined=r;socket.join(r.room_code);db.prepare('UPDATE room_players SET connected=1,last_seen_at=? WHERE room_id=? AND user_id=?').run(now(),r.id,uid);const g=gameByRoom(r.id);if(g&&g.status!=='GAME_FINISHED'){const st=JSON.parse(g.state_json);const me=st.players.find(p=>p.id===uid);if(me){me.connected=true;if(st.phase==='PAUSED'){const allBack=st.players.every(p=>p.connected);if(allBack){st.phase=st.pausedFromPhase||'PLAYING';delete st.pausedFromPhase;st.version++;saveGame(g.id,st);systemChat(r.id,`${getUser(uid).display_name} reconnected — all players are back, game resumed.`);}}emitGame(r,st);}}broadcastRoom(r.id);});
 socket.on('TOGGLE_READY',()=>{if(!joined)return;const rp=db.prepare('SELECT * FROM room_players WHERE room_id=? AND user_id=?').get(joined.id,uid);if(!rp||joined.status!=='WAITING')return;db.prepare('UPDATE room_players SET ready=? WHERE room_id=? AND user_id=?').run(rp.ready?0:1,joined.id,uid);broadcastRoom(joined.id);});
 socket.on('LEAVE_ROOM',()=>{if(!joined)return;const r=joined;if(r.status!=='WAITING')return socket.emit('ERROR',{error:'CANNOT_LEAVE_DURING_GAME'});db.prepare('DELETE FROM room_players WHERE room_id=? AND user_id=?').run(r.id,uid);if(r.host_id===uid){const next=db.prepare('SELECT * FROM room_players WHERE room_id=? ORDER BY seat LIMIT 1').get(r.id);if(next)db.prepare('UPDATE rooms SET host_id=? WHERE id=?').run(next.user_id,r.id);}broadcastRoom(r.id);socket.leave(r.room_code);joined=null;});
 socket.on('KICK_PLAYER',({userId})=>{if(!joined)return;if(joined.host_id!==uid)return socket.emit('ERROR',{error:'HOST_ONLY'});if(userId===uid)return;db.prepare('DELETE FROM room_players WHERE room_id=? AND user_id=?').run(joined.id,userId);connections.get(userId)?.emit('KICKED');broadcastRoom(joined.id);});
 socket.on('START_GAME',()=>{if(!joined)return;if(joined.host_id!==uid)return socket.emit('ERROR',{error:'HOST_ONLY'});const r=db.prepare('SELECT * FROM rooms WHERE id=?').get(joined.id);if(!['WAITING','FINISHED'].includes(r.status))return socket.emit('ERROR',{error:'ROOM_ALREADY_PLAYING'});const ps=roomPlayers(r.id);if(ps.length<2)return socket.emit('ERROR',{error:'NEED_TWO_PLAYERS'});if(ps.some(x=>!x.ready))return socket.emit('ERROR',{error:'ALL_PLAYERS_MUST_READY'});const st=initialState(ps.map(x=>({id:x.user_id,name:x.display_name,avatar:x.avatar})),JSON.parse(r.settings_json));const gid=newId();db.prepare('INSERT INTO games(id,room_id,mode,status,state_json,state_version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(gid,r.id,r.mode,st.phase,JSON.stringify(st),st.version,now(),now());db.prepare('UPDATE rooms SET status=\'PLAYING\',updated_at=? WHERE id=?').run(now(),r.id);systemChat(r.id,'Game started.');io.to(r.room_code).emit('GAME_STARTED');emitGame(r,st);broadcastRoom(r.id);});
 socket.on('CHAT_MESSAGE',({message})=>{if(!joined)return;const msg=String(message||'').trim().slice(0,300);if(!msg)return;const recent=db.prepare("SELECT COUNT(*) n FROM chat_messages WHERE room_id=? AND user_id=? AND kind='CHAT' AND created_at>?").get(joined.id,uid,new Date(Date.now()-5000).toISOString()).n;if(recent>=5)return socket.emit('ERROR',{error:'CHAT_RATE_LIMIT'});const u=getUser(uid);db.prepare('INSERT INTO chat_messages(room_id,user_id,message,kind,created_at) VALUES(?,?,?,?,?)').run(joined.id,uid,msg,'CHAT',now());io.to(joined.room_code).emit('CHAT_MESSAGE_CREATED',{userId:uid,message:msg,kind:'CHAT',createdAt:now(),displayName:u.display_name,avatar:u.avatar});});
 socket.on('GAME_ACTION',({type,cardId,chosenColor,clientActionId,stateVersion})=>{if(!joined)return;const r=db.prepare('SELECT * FROM rooms WHERE id=?').get(joined.id);const g=gameByRoom(r.id);if(!g)return;const st=JSON.parse(g.state_json);if(st.phase==='PAUSED')return socket.emit('GAME_ACTION_REJECTED',{clientActionId,reason:'GAME_PAUSED'});if(Number(stateVersion)!==Number(st.version))return socket.emit('GAME_ACTION_REJECTED',{clientActionId,reason:'STALE_STATE',state:visibleState(st,uid)});const action={type,cardId,chosenColor,targetPlayerId};const check=validateAction(st,uid,action);if(!check.ok)return socket.emit('GAME_ACTION_REJECTED',{clientActionId,reason:check.reason});try{const ns=applyAction(st,uid,action);ns.version=st.version+1;saveGame(g.id,ns,ns.phase==='GAME_FINISHED'?'GAME_FINISHED':ns.phase);if(ns.phase==='GAME_FINISHED'){const result=finalizeGame(r,g,ns);ns.result=[...result.values()];saveGame(g.id,ns,'GAME_FINISHED');db.prepare('UPDATE rooms SET status=\'FINISHED\',updated_at=? WHERE id=?').run(now(),r.id);systemChat(r.id,`Game finished. Winner: ${getUser(ns.winnerId)?.display_name||'—'}`);}emitGame(r,ns);socket.emit('GAME_ACTION_ACCEPTED',{clientActionId,version:ns.version});broadcastRoom(r.id);}catch(e){socket.emit('GAME_ACTION_REJECTED',{clientActionId,reason:e.message});}});
 socket.on('disconnect',()=>{if(connections.get(uid)===socket)connections.delete(uid);if(!joined)return;db.prepare('UPDATE room_players SET connected=0,last_seen_at=? WHERE room_id=? AND user_id=?').run(now(),joined.id,uid);const g=gameByRoom(joined.id);if(g&&g.status!=='GAME_FINISHED'){const st=JSON.parse(g.state_json);const p=st.players.find(x=>x.id===uid);if(p){p.connected=false;st.pausedFromPhase=st.phase;st.phase='PAUSED';st.version++;saveGame(g.id,st,'PAUSED');systemChat(joined.id,`${getUser(uid).display_name} disconnected — game paused.`);io.to(joined.room_code).emit('GAME_PAUSED',{userId:uid});emitGame(joined,st);}}broadcastRoom(joined.id);});
});

const PORT=Number(process.env.PORT||3000);server.listen(PORT,()=>console.log(`CIRCUS LUNGJUN BETA running on http://localhost:${PORT}`));
